DROP DATABASE IF EXISTS sekai;
CREATE DATABASE sekai;
USE sekai;

DROP TABLE IF EXISTS majors;
CREATE TABLE IF NOT EXISTS majors (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(63) UNIQUE NOT NULL,
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS grades;
CREATE TABLE IF NOT EXISTS grades (
    id INT PRIMARY KEY,
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS classes;
CREATE TABLE IF NOT EXISTS classes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(63) UNIQUE NOT NULL,
    major_id INT NOT NULL,
    grade_id INT NOT NULL,
    capacity INT NOT NULL DEFAULT 50,
    CONSTRAINT fk_class_id_major FOREIGN KEY (major_id) REFERENCES majors(id),
    CONSTRAINT fk_class_id_grade FOREIGN KEY (grade_id) REFERENCES grades(id),
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(63) NOT NULL,
    email VARCHAR(127) UNIQUE NOT NULL,
    identifier VARCHAR(31) UNIQUE NOT NULL,
    role ENUM('STUDENT', 'TEACHER', 'VP', 'ADMIN') NOT NULL,
    class_id INT,
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_student_class FOREIGN KEY (class_id) REFERENCES classes(id) ON UPDATE CASCADE ON DELETE RESTRICT
); -- Plus Laravel's own columns

DROP TABLE IF EXISTS subjects;
CREATE TABLE IF NOT EXISTS subjects (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(63) UNIQUE NOT NULL,
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS majors_subjects;
CREATE TABLE IF NOT EXISTS majors_subjects (
    major_id INT NOT NULL,
    subject_id INT NOT NULL,
    PRIMARY KEY (major_id, subject_id),
    CONSTRAINT fk_majors_subjects_id_major FOREIGN KEY (major_id) REFERENCES majors(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_majors_subjects_id_subject FOREIGN KEY (subject_id) REFERENCES subjects(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS grades_subjects;
CREATE TABLE IF NOT EXISTS grades_subjects (
    grade_id INT NOT NULL,
    subject_id INT NOT NULL,
    PRIMARY KEY (grade_id, subject_id),
    CONSTRAINT fk_grades_subjects_id_grade FOREIGN KEY (grade_id) REFERENCES grades(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_grades_subjects_id_subject FOREIGN KEY (subject_id) REFERENCES subjects(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS academic_semesters;
CREATE TABLE IF NOT EXISTS academic_semesters (
    id INT AUTO_INCREMENT PRIMARY KEY,
    academic_year CHAR(9) NOT NULL,
    semester TINYINT NOT NULL,
    UNIQUE(academic_year, semester),
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS lesson_periods;
CREATE TABLE IF NOT EXISTS lesson_periods (
    id INT AUTO_INCREMENT PRIMARY KEY,
    weekday TINYINT(6) NOT NULL,
    time_begin TIME NOT NULL,
    time_end TIME NOT NULL,
    semester_id INT NOT NULL,
    UNIQUE(weekday, time_begin, time_end, semester_id),
    CONSTRAINT fk_period_semester_id FOREIGN KEY (semester_id) REFERENCES academic_semesters(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS activities;
CREATE TABLE IF NOT EXISTS activities (
    id INT AUTO_INCREMENT PRIMARY KEY,
    subject_id INT NOT NULL,
    teacher_id INT NOT NULL,
    period_id INT NOT NULL,
    class_id INT NOT NULL,
    UNIQUE (subject_id, teacher_id, period_id, class_id),
    CONSTRAINT fk_activity_subject_id FOREIGN KEY (subject_id) REFERENCES subjects(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_activity_teacher_id FOREIGN KEY (teacher_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_activity_period_id FOREIGN KEY (period_id) REFERENCES lesson_periods(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_activity_class_id FOREIGN KEY (class_id) REFERENCES classes(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS activity_students;
CREATE TABLE IF NOT EXISTS class_students (
    student_id INT NOT NULL,
    activity_id INT NOT NULL,
    PRIMARY KEY (student_id, activity_id),
    CONSTRAINT fk_activity_students_student_id FOREIGN KEY (student_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_activity_students_class_id FOREIGN KEY (activity_id) REFERENCES activities(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS activity_forms;
CREATE TABLE IF NOT EXISTS activity_forms (
    id INT AUTO_INCREMENT PRIMARY KEY,
    activity_id INT NOT NULL,
    activity_date DATE DEFAULT (CURRENT_DATE),
    UNIQUE (activity_id, activity_date),
    CONSTRAINT fk_activity_form_activity_id FOREIGN KEY (activity_id) REFERENCES activities(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS activity_presences;
CREATE TABLE IF NOT EXISTS activity_presences (
    id INT AUTO_INCREMENT PRIMARY KEY,
    form_id INT NOT NULL,
    student_id INT NOT NULL,
    UNIQUE (form_id, student_id),
    score TINYINT(3) NOT NULL,
    CONSTRAINT fk_presence_form_id FOREIGN KEY (form_id) REFERENCES activity_forms(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_presence_student_id FOREIGN KEY (student_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS activity_reports;
CREATE TABLE IF NOT EXISTS activity_reports (
    presence_id INT PRIMARY KEY,
    score TINYINT(3) NOT NULL,
    topic VARCHAR(255) NOT NULL,
    details TEXT NOT NULL,
    CONSTRAINT fk_report_presence_id FOREIGN KEY (presence_id) REFERENCES activity_presences(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS score_distributions;
CREATE TABLE IF NOT EXISTS score_distributions (
    activity_id INT,
    name VARCHAR(255),
    weight INT NOT NULL DEFAULT 1,
    PRIMARY KEY (activity_id, name),
    CONSTRAINT fk_score_distribution_activity_id FOREIGN KEY (activity_id) REFERENCES activities(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS student_scores;
CREATE TABLE IF NOT EXISTS student_scores (
    activity_id INT,
    student_id INT,
    name VARCHAR(255),
    score TINYINT NOT NULL DEFAULT 0 CHECK (score BETWEEN 0 AND 100),
    PRIMARY KEY (activity_id, student_id, name),
    CONSTRAINT fk_student_score_activity_id FOREIGN KEY (activity_id) REFERENCES activities(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_student_score_student_id FOREIGN KEY (student_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS announcements;
CREATE TABLE IF NOT EXISTS announcements (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    subtitle VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    sender_id INT NOT NULL,
    scope ENUM('SPECIFIC-CLASS', 'CLASS-TAUGHT', 'SPECIFIC-GRADE', 'TEACHERS', 'PUBLIC') NOT NULL,
    activity_id INT,
    grade_id INT,
    CONSTRAINT fk_announcement_activity_id FOREIGN KEY (activity_id) REFERENCES activities(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_announcement_grade_id FOREIGN KEY (grade_id) REFERENCES grades(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);